#!/bin/sh -e

if [ "$1" = "configure" ] ; then
	if [ ! -f /etc/default/instance_configs.cfg ]; then 
		cp -a "/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/instance_configs.cfg" /etc/default/
	fi
fi

if deb-systemd-helper --quiet was-enabled 'google-shutdown-scripts.service'; then
  deb-systemd-helper purge 'google-shutdown-scripts.service' >/dev/null || true
fi

export _DEB_SYSTEMD_HELPER_DEBUG=1

#DEBHELPER#
