#!/bin/sh -e

if [ "$1" = "install" ] ; then
  if deb-systemd-helper --quiet was-enabled 'google-shutdown-scripts.service'; then
    deb-systemd-helper purge 'google-shutdown-scripts.service' >/dev/null || true
  fi
fi

export _DEB_SYSTEMD_HELPER_DEBUG=1

#DEBHELPER#

